apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: homelab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

      imagePullSecrets:
        - name: registry-creds
      volumes:
        - name: tmp
          emptyDir: {}
      containers:
        - name: backend
          image: 192.168.122.96:30500/homelab-backend:${CI_COMMIT_SHA}
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            runAsUser: 100
            runAsGroup: 101
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          ports:
            - containerPort: 3001
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          env:
            - name: PORT
              value: "3001"
            - name: NODE_ENV
              value: "production"
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            - name: tmp
              mountPath: /tmp
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: homelab
spec:
  selector:
    app: backend
  ports:
    - port: 3001
      targetPort: 3001
