depends_on:
  - build

when:
  - event: pull_request
  - event: push
    branch: main

steps:
  prepare-docker-auth:
    image: alpine
    environment:
      DOCKER_CONFIG_JSON:
        from_secret: docker_config_json
    commands:
      - mkdir -p /woodpecker/src/.docker-auth
      - echo "$DOCKER_CONFIG_JSON" > /woodpecker/src/.docker-auth/config.json

  validate:
    image: gcr.io/gcp-runtimes/container-structure-test
    environment:
      DOCKER_CONFIG: /woodpecker/src/.docker-auth
    entrypoint:
      - /container-structure-test
      - test
      - --driver
      - tar
      - --image
      - 192.168.122.96:30500/homelab-backend:${CI_COMMIT_SHA}
      - --config
      - backend/container-structure-test.yml
