depends_on:
  - build

when:
  - event: pull_request
  - event: push
    branch: main

steps:
  validate:
    image: gcr.io/gcp-runtimes/container-structure-test
    entrypoint:
      - /container-structure-test
      - test
      - --driver
      - tar
      - --image
      - 192.168.122.96:30500/homelab-backend:${CI_COMMIT_SHA}
      - --config
      - backend/container-structure-test.yml
